### ISSUE TITLE
Continue DMX when device is locked

### ISSUE THREAD

**Issue by dfredell** [dfredell/AuroraDMX#3]

**Comment by amenk** [comment]
Experienced this problem, especially if a Chase is on it is relevant

**Comment by Lutzion** [comment]
Probably the solution can be found here:
[https://developer.android.com/training/scheduling/wakelock](https://developer.android.com/training/scheduling/wakelock)

Detailed examples:
[https://stackoverflow.com/questions/5712849/how-do-i-keep-the-screen-on-in-my-app](https://stackoverflow.com/questions/5712849/how-do-i-keep-the-screen-on-in-my-app)
https://stackoverflow.com/questions/4195682/android-disable-screen-timeout-while-app-is-running

Actually it does not make the chase work when locked, but it avoides locking.
Maybe that is a solution too.

The easiest solution: Just add 
`android:keepScreenOn="true"`
in 
- activity_chase.xml
and maybe
- activity_cue.xml
- activity_main.xml

**Comment by dfredell** [comment]
android:keepScreenOn looks like a good option. I would accept a MR, or try and find time in life to code and test this.
